### ISSUE TITLE
Discrepancy between Training Instructions and Codebase

### ISSUE THREAD

**Issue by saimunur** [JiLiBIT/RangePlace#1]
Hi there,

First, I'd like to thank you for creating the RangePlace codebase. I'm really impressed with the work you've done!

I'm trying to train the model, but I've noticed some discrepancies between the training instructions and the provided codebase.

Specifically, the instructions mention a training folder with `generating_queries` files, but I couldn't find this folder within the codebase. Additionally, there's no mention of a `training` folder in the code itself.

Could you please clarify how to prepare the dataset and initiate training using the current codebase? Any guidance you can provide would be greatly appreciated.

Thanks again for your work on this project!

**Comment by jerichoji** [comment]
Hi,
Thank you for your interests.
We have fixed the instructions in README, and update training codes.
